[profile.default]
src = 'contracts/'                                                   
test = 'foundry/test'                                                 
out = 'foundry/out'                                                   
libs = ['foundry/lib']                                                
remappings = ['ds-test/=foundry/lib/ds-test/src/', 'forge-std/=foundry/lib/forge-std/src/', '@openzeppelin/=node_modules/@openzeppelin']   
evm_version = 'istanbul'                                        
solc_version = '0.6.12'                                      
sender = '0x1BEeEeeEEeeEeeeeEeeEEEEEeeEeEeEEeEeEeEEe'         
tx_origin = '0x1BEeEeeEEeeEeeeeEeeEEEEEeeEeEeEEeEeEeEEe'      
initial_balance = '0xffffffffffffffffffffffff'                
gas_limit = 9223372036854775800                               
gas_price = 0                                                 
block_timestamp = 0                                           
gas_reports = ["*"]
eth_rpc_url = 'https://rpc.gnosis.gateway.fm'
verbosity = 3
# libraries=["contracts/protocol/libraries/logic/ReserveLogic.sol:ReserveLogic:0x1B0348c67D01a46627CE1d8f9e2E218c9eaE9966","contracts/protocol/libraries/logic/ValidationLogic.sol:ValidationLogic:0x09bf5d4dff196c000fb735f94e4b22340b25e678"]

[profile.default.optimizer_details]
constantOptimizer = true
yul = true

[profile.default.optimizer_details.yulDetails]
stackAllocation = true
optimizerSteps = 'dhfoDgvulfnTUtnIf'
optimizer_runs = 200  